# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_sgrimee age1rn7gsv9e2dwhjt20p5gsnydrnqyu5c339gku2h9agq8kamqynqqs8v4m7u
  - &server_cirice age1vxel6p05epr67nz6endwz6f23drk7r0yve6gjcrf57ypjvl7hq6s68nvjd
  - &server_dracula age166rqyrhv0rl20k3ga2v46tk3kge6vx7ahnm3v8xzv00zdfxya3pqjatxcw
  - &server_mbp_15_2018 age1g3yuwa905tsc5ylx58ax3aq882aet8kluyt8jshntzsza6h9cfuqg9z38m
  - &server_mbp_16_2023 age18xqlukfwr35mumgre56807raq0thq6ps6njdl9vfn8agw4qjlavs5f8qmj
  - &server_nixair age19axf2ac6886gvqxp95wxwhcs4xnqadyg9m6ckhnfvrhs4nasyexqyzet0n
  - &server_legion age1sdjn90rr0e8vtvq9wt92rsw6vajmmrn5yj8dvzfardyrzj4uzpxs3zjcdx
creation_rules:
  # Host-specific secrets
  - path_regex: secrets/nixair/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_sgrimee
        - *server_nixair
  - path_regex: secrets/cirice/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_sgrimee
        - *server_cirice
  - path_regex: secrets/dracula/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_sgrimee
        - *server_dracula
  - path_regex: secrets/legion/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_sgrimee
        - *server_legion
  - path_regex: secrets/mbp_16_2023/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_sgrimee
        - *server_mbp_16_2023
  # Shared secrets (accessible by all hosts)
  - path_regex: secrets/shared/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_sgrimee
        - *server_cirice
        - *server_dracula
        - *server_mbp_15_2018
        - *server_mbp_16_2023
        - *server_nixair
        - *server_legion
  # Legacy: existing root-level secrets (for backward compatibility)
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_sgrimee
        - *server_cirice
        - *server_dracula
        - *server_mbp_15_2018
        - *server_mbp_16_2023
        - *server_nixair
        - *server_legion
