{
  config,
  lib,
  pkgs,
  hostCapabilities ? {},
  ...
}: let
  cfg = config.programs.niri;

  # Safely read keyboard profile from host capabilities (default: "apple")
  fnKeyProfile =
    if hostCapabilities ? hardware && hostCapabilities.hardware ? keyboard && hostCapabilities.hardware.keyboard ? fnKeyProfile
    then hostCapabilities.hardware.keyboard.fnKeyProfile
    else "apple";

  # Safely read terminal from host capabilities (default: "alacritty")
  terminal =
    if hostCapabilities ? environment && hostCapabilities.environment ? terminal
    then hostCapabilities.environment.terminal
    else "alacritty";

  # Validate profile is one of the supported options
  validProfiles = ["apple" "framework" "standard"];
  isValidProfile = lib.elem fnKeyProfile validProfiles;

  # Load base configuration
  baseConfig = import ./config.nix {inherit pkgs terminal;};

  # Load keyboard profile based on fnKeyProfile
  keymap = import ./keymaps/${fnKeyProfile}.nix {inherit pkgs;};

  # Generate complete niri config.kdl
  niriConfig = pkgs.writeText "niri-config.kdl" ''
    // Niri Configuration (Generated by Nix)
    // Keyboard Profile: ${fnKeyProfile}
    // This file is auto-generated - do not edit manually

    ${baseConfig.input}

    ${baseConfig.outputs}

    ${baseConfig.layout}

    ${baseConfig.startup}

    ${baseConfig.animations}

    ${baseConfig.windowRules}

    binds {
        // Function key bindings (profile-specific)
        ${keymap.functionKeys}

        // Universal keybindings
        ${baseConfig.universalBindings}
    }
  '';
in {
  options.programs.niri = {
    enable = lib.mkEnableOption "Niri window manager";
    modifier = lib.mkOption {
      type = lib.types.str;
      default = "Mod1";
      description = "Niri modifier key (Mod1 = Alt, Mod4 = Super/Windows)";
    };
  };

  config = lib.mkMerge [
    # Enable automatically when module imported (can be disabled explicitly)
    {programs.niri.enable = lib.mkDefault true;}

    # Throw error if invalid profile
    (
      if !isValidProfile
      then (throw "Invalid niri fnKeyProfile '${fnKeyProfile}'. Must be one of: ${builtins.concatStringsSep ", " validProfiles}")
      else {}
    )

    # Main configuration
    (lib.mkIf cfg.enable {
      # Use the generated niri config file
      xdg.configFile."niri/config.kdl" = {
        source = niriConfig;
      };
    })
  ];
}
