{ ... }: [
  "1password"
  "1password-cli"
  "ableton-live-suite"
  "alfred"
  "arc"
  "arturia-software-center"
  "balenaetcher"
  "bambu-studio"
  "battery"
  "busycal"
  "cocoapacketanalyzer"
  "curseforge"
  "daisydisk"
  "devonthink"
  "discord"
  "docker-desktop"
  "etrecheckpro"
  "firefox"
  "ghostty"
  "gitup-app"
  "google-chrome"
  "guitar-pro"
  "home-assistant"
  "inkscape"
  "iterm2"
  "itermai"
  "karabiner-elements"
  "loopback"
  "macloggerdx"
  "menuwhere"
  "microsoft-auto-update"
  "microsoft-teams"
  "microsoft-excel"
  "microsoft-powerpoint"
  "microsoft-outlook"
  "microsoft-word"
  "midi-monitor"
  "mongodb-compass"
  # "mounty"
  "mqtt-explorer"
  # "nikitabobko/tap/aerospace" # Now managed via services.aerospace
  "neo4j-desktop"
  "notunes"
  "obsidian"
  "omnifocus"
  # "orcaslicer"
  # "paragon-extfs"
  "plex"
  # "qth"
  "raspberry-pi-imager"
  "raycast"
  # "rectangle"
  "serial"
  "shortcat"
  "signal"
  "silicon-labs-vcp-driver"
  "steam"
  "slack"
  "sonos"
  "spotify"
  "synology-surveillance-station-client"
  "textsniper"
  "tqsl"
  "ubersicht"
  "utm"
  "visual-studio-code"
  "visual-studio-code@insiders"
  "vlc"
  "wch-ch34x-usb-serial-driver"
  "whatsapp"
  "wifi-explorer"
  "winbox"
  "windsurf"
  "wireshark-app"
]
