{...}: [
  "1password"
  "ableton-live-suite"
  "alfred"
  "arc"
  "balenaetcher"
  "bambu-studio"
  "battery"
  "busycal"
  "devonthink"
  "discord"
  "firefox"
  "gitup"
  "guitar-pro"
  "insomnia"
  "karabiner-elements"
  "logi-options-plus"
  "loopback"
  "macloggerdx"
  "microsoft-teams"
  "midi-monitor"
  # "mounty"
  "notunes"
  "obsidian"
  "orcaslicer"
  # "paragon-extfs"
  "plex"
  "qth"
  # "raycast"
  "rectangle"
  "serial"
  "signal"
  "sonos"
  "spotify"
  "synology-surveillance-station-client"
  "telegram"
  "tqsl"
  "utm"
  # "visual-studio-code"
  "vlc"
  "wch-ch34x-usb-serial-driver"
  "whatsapp"
  # "zed"
]
